### ISSUE TITLE
Add flipped flipper mode to gampad1

### ISSUE THREAD

**Issue by DarkLordZach** [SwampBots-FTC-10497/VelocityVortex2016#18]
Make it so the flipper joystick (left) on gamepad 1 swaps between down is up and up is down to down is down and up is up when the mode button is activated.

Thanks,
DarkLordZach

**Comment by CaptainFlareon** [comment]
It's currently in progress, but I need to figure out where to get the flipper motor Object imported from.

**Comment by DarkLordZach** [comment]
1. Don't capitalize object, it is not a proper noun.
2. Don't worry about imports, Android Studio does it automatically.
3. You should not be accessing the flipper motor object, use the high-level methods instead.

Ask Jarrod for help, he knows my conventions and stuff really well.

**Comment by DarkLordZach** [comment]
Basically,
Find line 77 & 78 and replace the firmware.driveLinear() parts with the flipper linear methods and make the speed -1.0 for up and 1.0 for down. Commit after that. Then test the code and if it works, make the PR, otherwise fix and test until it works.

**Comment by DarkLordZach** [comment]
<img width="662" alt="screen shot 2016-12-16 at 11 09 58 am" src="https://cloud.githubusercontent.com/assets/5064800/21269331/5a944a86-c380-11e6-8801-d277722519f4.png">
