### ISSUE TITLE
Stuck in stop crash in autonomous and driver control.

### ISSUE THREAD

**Issue by kawaiiPlatypus** [SwampBots-FTC-10497/VelocityVortex2016#20]
When you hit the stop button on the driver phone after initializing but before starting the op mode, it causes the app to crash and restart with the error message "Op mode stuck in stop () restarting robot controller app." After it crashes, the unused flipper motor and the ball lifter activate until the app closes itself and restarts

**Comment by DarkLordZach** [comment]
Looking into it. Please provide a picture of the error.

**Comment by DarkLordZach** [comment]
Also, since this is relating to how the firmware handles stop requests, I will adjust the labels/assignees.

**Comment by DarkLordZach** [comment]
Can you also tell me the exact moment you pressed stop? That will narrow down the culprit considerably.

**Comment by kawaiiPlatypus** [comment]
![screenshot_2016-12-15-21-15-13 1](https://cloud.githubusercontent.com/assets/17530853/21249871/275d3266-c30f-11e6-820e-717c45831278.png)

**Comment by DarkLordZach** [comment]
Bruh thats driver control...

**Comment by DarkLordZach** [comment]
No wonder I couldn't find the error...

**Comment by DarkLordZach** [comment]
Fixed with #21.

**Comment by kawaiiPlatypus** [comment]
The picture was another error, the proper picture is 
![img_20161215_214555775_hdr](https://cloud.githubusercontent.com/assets/17530853/21250052/38964bc0-c310-11e6-8908-b2a2f8c17eb9.jpg)

**Comment by DarkLordZach** [comment]
k fine

**Comment by DarkLordZach** [comment]
Driver control was fixed in #21. I'll look into this, please review #21.

**Comment by DarkLordZach** [comment]
Added to #21. Please check my comments there in a bit to see my explanation. I want to make this a learning experience. 👍
