### ISSUE TITLE
Crash in Driver Control.

### ISSUE THREAD

**Issue by kawaiiPlatypus** [SwampBots-FTC-10497/VelocityVortex2016#22]
After hitting init in DC, this error appears, and you have to restart. 
![screenshot_2016-12-15-21-15-13 1](https://cloud.githubusercontent.com/assets/17530853/21250136/e0889482-c310-11e6-8c00-9678b3b6dadb.png)

**Comment by DarkLordZach** [comment]
I covered this in #21, because you put this picture in #20.
