### ISSUE TITLE
Add a turnDegrees method

### ISSUE THREAD

**Issue by kawaiiPlatypus** [SwampBots-FTC-10497/VelocityVortex2016#23]
We currently have a turnEncoderCount method. I am manually doing the math to convert encoder counts into degrees turned. Can we add a method to perform this function?

**Comment by DarkLordZach** [comment]
If you post the formula in this issue, I will have it done!

**Comment by DarkLordZach** [comment]
Changed name to keep with FWDriveSnatch convention.

**Comment by kawaiiPlatypus** [comment]
![img_20161216_110239246_li 2](https://cloud.githubusercontent.com/assets/17530853/21269512/f8848eb8-c380-11e6-90ed-ff7507df796b.jpg)
P(i(x)) x/WHEEL_RADIUS //the percentage of a full turn
E(P(i(x))) = x * ENCODER_COUNTS_PER_ROTATION
Therefore: for x = degree turn, Y = encoder counts per x degree turn = (((2π(TURN_RADIUS)/360)(x))/4.0) * ENCODER_COUNTS_PER_ROTATION

**Comment by kawaiiPlatypus** [comment]
I would have made a local method, but I don't know how to access values like ENCODER_COUNTS_PER_ROTATION

**Comment by DarkLordZach** [comment]
You should not have made a local method anyway, this issue is assigned to
me. I will fix it later.

**Comment by DarkLordZach** [comment]
Here is the final formula I used:

![codecogseqn](https://cloud.githubusercontent.com/assets/5064800/21277375/0553539a-c3a4-11e6-9e0a-6855dff250f5.png)

Where `t(x)` is number encode counts,`x` is the degrees to turn, `d` is the diameter of the wheels, and `e` is the encoder counts per inch.

**Comment by DarkLordZach** [comment]
Wait nvm, measure the robot from center of left drive wheel to right and put that here.

**Comment by kawaiiPlatypus** [comment]
The distance between the wheels is ~15 inches, if that's what you're asking

**Comment by kawaiiPlatypus** [comment]
I went with 7.5 in my calculations

**Comment by DarkLordZach** [comment]
Please remeasure. Just want to be sure. Put the end between the two parts of the omni wheels.

**Comment by kawaiiPlatypus** [comment]
the omni wheels are not the drive wheels and are aligned differently. The distance between the drive wheels is 14.25  inches. The mathematical turning radius is therefore 7.125 inches.

**Comment by DarkLordZach** [comment]
Okay, wasn't thinking about omni/drive wheels.

**Comment by DarkLordZach** [comment]
Solved in #29.
