### ISSUE TITLE
Assign flip load method to X button.

### ISSUE THREAD

**Issue by DarkLordZach** [SwampBots-FTC-10497/VelocityVortex2016#25]
Should be at 1.0 speed. (Gamepad 1)

**Comment by DarkLordZach** [comment]
What fimware.flipLoad() does is, starting from a straight down position of the flipper, lifts and shoots and returns to down position. If you think this wouldn't be helpful in DC, click close issue.

**Comment by kawaiiPlatypus** [comment]
We would need to keep track of what is down, probably based off our set up.
Then add the values from flipLoad to the current total of forward and
backwards encoder counts.

**Comment by kawaiiPlatypus** [comment]
We will add in a simple call of this method right now, and look into full implementation later

**Comment by DarkLordZach** [comment]
Making that an issue. Plz just bind the method right now for tomorrow and I promise me and Benji will look into it.

**Comment by kawaiiPlatypus** [comment]
Thats what I said I'd do.

**Comment by DarkLordZach** [comment]
Sounds good. If you need help tonight, Allo me. :)

**Comment by kawaiiPlatypus** [comment]
Implementation of this will be dependent on our ability to keep track of the flipper's position in #30
