### ISSUE TITLE
Precise movement options for DC

### ISSUE THREAD

**Issue by kawaiiPlatypus** [SwampBots-FTC-10497/VelocityVortex2016#27]
We have difficulty moving in small increments, so i propose a macro tho do just that.

On gamepad two, add more precise control when moving the left and right wheels around. Specifically, make the left and right d-pad buttons move their respective wheels, and the d-pad up and down would change the direction the wheels turn. For example, if I hit d-pad up, then hold d-pad left, the left wheel should move forward.

**Comment by DarkLordZach** [comment]
I think this is a good idea, Blake please take Jarrod layout, combine your input, list out what UDL&R on Gamepad 2 will do and then implement this.

**Comment by CaptainFlareon** [comment]
Specifically stated,
d-pad up: set drive motor direction to forward.
d-pad down: set drive motor direction to reverse.
these will only affect the following two commands...
d-pad left: move the left motor while held.
d-pad right: move the right motor while held.

For instance,
press d-pad up then hold d-pad right: right drive motor turns forward until d-pad right is released.

**Comment by DarkLordZach** [comment]
Solved in #28.
