### ISSUE TITLE
Vuforia tracking of center vortex.

### ISSUE THREAD

**Issue by DarkLordZach** [SwampBots-FTC-10497/VelocityVortex2016#41]

**Comment by kawaiiPlatypus** [comment]
After conversations had after the event, we reached a consensus that it would be more efficient to use a different camera interface than Vuforia, either our own or an open source one. Whereas Vuforia tracks a target 3-D object in 3-D space, we only need to know if a block of color is showing at a specific height in our field of view, and the number of pixels across that it takes up. From there we can interpret an angle and a distance.

**Comment by DarkLordZach** [comment]
This is not feasible for the state competition.
