### ISSUE TITLE
Mismatch of branches and team priorities

### ISSUE THREAD

**Issue by kawaiiPlatypus** [SwampBots-FTC-10497/VelocityVortex2016#54]
Currently, our branches are not aligned with the overall direction and decisions made by the team. We are focusing on the working on the _**main competition robot**_, the one we started and have been working on since the beginning of the season and the one that earns us any points at all. Therefore, this robot should have its latest fully working code residing in the Master branch. However, unless I am egregiously mistaken, it is currently in the swampbot_v1 branch.

I request that the current working robot code be placed in Master, while the TileRunner based robot's code is placed in a branch such as swampbot_v2

**Comment by DarkLordZach** [comment]
This cannot be done.
