### ISSUE TITLE
Remove various comments used in PR testing.

### ISSUE THREAD

**Issue by DarkLordZach** [SwampBots-FTC-10497/VelocityVortex2016#6]
I know there is one one line 14 in FrameHAL.java, 76 in DriverControl.java, and 13 in AutonomousRevision1Red.java.

Please remove these and check for any others.

Thanks,
Dark Lord Zach

PS. This is a practice issue... (It's still legit though.)

**Comment by CaptainFlareon** [comment]
Okay, I'll get on it later today.

**Comment by DarkLordZach** [comment]
Just make a PR for it.

**Comment by DarkLordZach** [comment]
Resolved in #24.
