### ISSUE TITLE
Autonomous Revision 1 and 2

### ISSUE THREAD

**Issue by DarkLordZach** [SwampBots-FTC-10497/VelocityVortex2016#7]
TBC there needs to be the four following Autonomous classes, fully operational and tested:

- AutonomousRevision1Red
- AutonomousRevision1Blue
- AutonomousRevision2Red
- AutonomousRevision2Blue
- AutonomousRevision3Red
- AutonomousRevision3Blue

The difference between Rev 1 and 2 is Rev 1 is shoot only and Rev 2 is Rev 1 and drive forward to cap ball. Rev 3 is from corner of field.

Rev 1 & 3 are crucial for Saturday, 2 is also very nice.

Thanks,
DarkLordZach

PS> Another 'practice' just to get the flow going.

**Comment by kawaiiPlatypus** [comment]
Fixed in #31
